lind-prog/Jobbox

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_form.scss
- app/views/user_job_searches/new.html.erb
- db/migrate/20240821102122_add_phone_to_users.rb
- db/migrate/20240821102145_add_address_to_users.rb
- db/migrate/20240821102253_add_diplome_to_users.rb
- db/migrate/20240821102317_add_experience_to_users.rb
- db/schema.rb
ajout du formulaire pour créer son job recherché 
ajout de colonne dans user pour mettre age, tel, adresse, exp, diplôme
> form userjob search

- app/controllers/user_job_searches_controller.rb
- db/seeds.rb
Création de la méthode de matches basique, sans filtrage de critères, entre le UserJobSearches et Offer.all pour la redirection sur la map intéractive (version 1 non développé)
> Creation matches v1 sans filtrage

- .gitignore
- app/controllers/user_job_searches_controller.rb
Réparation de la redirection de la page Completer mon profil à la map des offres
> Add dotenv-rails&matches path

- app/assets/stylesheets/pages/_home_page.scss
- app/assets/stylesheets/pages/_index.scss
- app/javascript/controllers/index.js
- app/javascript/controllers/scroll_animation_controller.js
- app/views/offers/show.html.erb
- app/views/pages/home.html.erb
- db/seeds.rb
premiere version de la home page reste a faire
> home page v1

- app/models/candidacy.rb
- app/models/message.rb
- app/models/offer.rb
- app/models/user.rb
- app/models/user_job_search.rb
ajout des validations sur les models (presence true)
ajout des dependent destroy sur les models (si user est supprimé sa candidature, profil, offre, matches etc sont supprimés)
> validation et dependent destroy

- app/views/matches/_info_window.html.erb
ajout de la redirection du bouton "Voir l'offre" vers la show de l'offre
> redirection sur offer show

- app/controllers/matches_controller.rb
- app/controllers/user_job_searches_controller.rb
> premiere version du filtrage des matches sur les offres

- app/assets/stylesheets/pages/_map.scss
- app/controllers/user_job_searches_controller.rb
- app/views/offers/show.html.erb
- db/migrate/20240823110447_add_description_to_offers.rb
- db/schema.rb
- db/seeds.rb
matches userjobsearches à offres
ajout d'une colonne DESCRTIPTION dans le SEED ----> FAIRE DB MIGRATE
> front, matches, description

- app/assets/stylesheets/pages/_map.scss
- app/views/matches/index.html.erb
CSS de la MAP POSTION + html avec ajout col et row pour positon
> reposition map par rapport legende

- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_home_page.scss
- app/views/users/show.html.erb
> Paufinage dahsboard

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_my_candidacies.scss
- app/controllers/candidacies_controller.rb
- app/views/candidacies/my_candidacies.html.erb
création de la page my_candidacies
> mes candidatures

- app/assets/stylesheets/pages/_my_candidacies.scss
- app/controllers/candidacies_controller.rb
- app/models/candidacy.rb
- app/views/candidacies/my_candidacies.html.erb
- app/views/offers/show.html.erb
- db/migrate/20240826103159_change_status_to_be_integer_in_candidacies.rb
- db/schema.rb
PAGE my_candidacies avec liste des candidatures et leurs status 
FAIRE DB:MIGRATE car nouvelle migration
> my_candidacies

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/pages/_chatroom.scss
- app/controllers/chatrooms_controller.rb
- app/controllers/messages_controller.rb
- app/javascript/controllers/reset_form_controller.js
- app/models/message.rb
- app/views/chatrooms/show.html.erb
- app/views/messages/_message.html.erb
- config/application.rb
- config/cable.yml
- db/schema.rb
chatroom v1 fonctionnel mais moche
> chatromm debut

- app/assets/stylesheets/pages/_tinder.scss
- app/controllers/candidacies_controller.rb
- app/controllers/user_job_searches_controller.rb
- app/controllers/users_controller.rb
- app/javascript/controllers/tinder_controller.js
- app/views/users/index.html.erb
- db/seeds.rb
swipe finito reste front normalement tout marche avec ori et linda
> swipe complet

- app/controllers/candidacies_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/pages/home.html.erb
- app/views/users/_calendrier.html.erb
- app/views/users/_jobseeker.html.erb
- app/views/users/_recruiter.html.erb
- app/views/users/show.html.erb
dash board en partial et route path
> Dashboardrecruiter

- app/assets/stylesheets/pages/_my_candidacies.scss
- app/controllers/candidacies_controller.rb
- app/models/candidacy.rb
- app/views/candidacies/_jobseekercandidacies.html.erb
- app/views/candidacies/_recruitercandidacies.html.erb
- app/views/candidacies/my_candidacies.html.erb
- app/views/users/_jobseeker.html.erb
- app/views/users/_recruiter.html.erb
- config/routes.rb
création de la page my_candidacies pour les recruteurs avec le status modifiable relié à la candidature du candidat
> My candidacies recruiter

- app/assets/stylesheets/pages/_chatroom.scss
- app/controllers/candidacies_controller.rb
- app/views/chatrooms/_list.html.erb
- app/views/chatrooms/index.html.erb
- app/views/chatrooms/show.html.erb
chatroom man pour côté recruiter ou candidat
> chatroom recruiter

- app/assets/stylesheets/pages/_tinder.scss
- app/views/users/index.html.erb
> swipe front v1

- app/assets/stylesheets/pages/_home_page.scss
- app/views/pages/home.html.erb
> home page finito de finito

- app/assets/stylesheets/pages/_tinder.scss
- app/views/users/index.html.erb
> front du swipe

- app/assets/stylesheets/pages/_tinder.scss
- app/controllers/candidacies_controller.rb
- app/javascript/controllers/tinder_controller.js
> finito swipe vraiment

- app/assets/stylesheets/pages/_form.scss
- app/views/user_job_searches/new.html.erb
> front form

- app/assets/stylesheets/pages/_chatroom.scss
- app/controllers/candidacies_controller.rb
- app/controllers/chatrooms_controller.rb
- app/javascript/controllers/highlight_controller.js
- app/views/candidacies/_recruitercandidacies.html.erb
- app/views/chatrooms/_chat.html.erb
- app/views/chatrooms/_list.html.erb
- app/views/chatrooms/index.html.erb
- db/migrate/20240829151420_change_match_level_in_candidacies.rb
- db/schema.rb
stimulus sur la chatroom 
ajout des match level visible sur la conversation entre recruteur et candidat
un peu de front
> stimulus chatroom and front

- app/models/user.rb
- app/views/users/_jobseeker.html.erb
- db/schema.rb
ajout des dernières candidatures sur le dashboard (3 dernières)
on a fait ce qu'on a pu pour le front svp merci
> candidatures sur dashboard

- app/assets/stylesheets/pages/_map.scss
- app/views/candidacies/_recruitercandidacies.html.erb
- app/views/chatrooms/index.html.erb
bouton reparé et couleur text map
> bouton reparé et couleur text map
